export const ON_CHANGE = "ON_CHANGE";
export const CLEAR_INPUT_VALUES = "CLEAR_INPUT_VALUES";
export const SET_ON_CHANGE = "SET_ON_CHANGE";
export const AUTH = {
  LOADING: "LOADING",
  LOAD_DATA: "LOAD_DATA",
  USER_DETAILS: "USER_DETAILS",
};
export const SIGN_UP = {
  LOADING_SIGN_UP: "LOADING_SIGN_UP",
  LOAD_DATA_SIGN_UP: "LOAD_DATA_SIGN_UP",
  USER_DETAILS_SIGN_UP: "USER_DETAILS_SIGN_UP",
};

export const TEACHER = {
  TEACHER_RESPONSE: "TEACHER_RESPONSE",
  VIEW_STUDENT: "VIEW_STUDENT",
  VIEW_SINGLE_STUDENT: "VIEW_SINGLE_STUDENT",
  STORE_QUESTIONS: "STORE_QUESTIONS",
  SUBJECT_NAME: "SUBJECT_NAME",
  STORE_NOTES: "STORE_NOTES",
  PREV_QUESTION: "PREV_QUESTION",
  SET_CURRENT_INDEX: "SET_CURRENT_INDEX",
  PREV_LOADING: "PREV_LOADING",
  REMOVE_QUESTION: "REMOVE_QUESTION",
  DISABLE_SUBJECT: "DISABLE_SUBJECT",
  CLEAR_ALL_ONSUBMIT: "CLEAR_ALL_ONSUBMIT",
  SAVE_ONCHANGE: "SAVE_ONCHANGE",
  VIEW_ALL_EXAM: "VIEW_ALL_EXAM",
  VIEW_SINGLE_EXAM: "VIEW_SINGLE_EXAM",
  SHOW_MODAL: "SHOW_MODAL",
  POST_PREVIOUS_VALUES: "POST_PREVIOUS_VALUES",
  DELETE_EXAM: "DELETE_EXAM",
  VERIFIED_STUDENTS: "VERIFIED_STUDENTS",
};

export const STUDENT = {
  ALL_EXAM_DATA: "ALL_EXAM_DATA",
  GIVE_EXAM: "GIVE_EXAM",
  RESPONSE: "RESPONSE",
  PROFILE: "PROFILE",
};
