export const AUTH = {
  LOADING: "LOADING",
  LOAD_DATA: "LOAD_DATA",
  USER_DETAILS: "USER_DETAILS",
};
export const SIGN_UP = {
  LOADING_SIGN_UP: "LOADING_SIGN_UP",
  LOAD_DATA_SIGN_UP: "LOAD_DATA_SIGN_UP",
  USER_DETAILS_SIGN_UP: "USER_DETAILS_SIGN_UP",
};

export const TEACHER = {
  VIEW_STUDENT: "VIEW_STUDENT",
  
}
